config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home', action: :home

  resources :achievements, only: %i[create destroy]

  namespace 'admin' do
    resources :imports
  end

  resources :assessment_attempts

  get '/certificate/:slug', action: :show, controller: 'programmes', as: :programme
  post '/certifcate/:slug/enrol', action: :create, controller: 'user_programme_enrolments', as: :user_programme_enrolment
  get '/certificate/:slug/complete', action: :complete, controller: 'programmes', as: :programme_complete
  get '/certificate/:slug/pending', action: :pending, controller: 'programmes', as: :programme_pending
  get '/certificate/:slug/view-certificate', action: :certificate, controller: 'programmes', as: :programme_certificate
  get '/certificate/cs-accelerator/diagnostic/:id', to: 'diagnostics/cs_accelerator#show', as: :cs_accelerator_diagnostic
  get '/certificate/primary-certificate/questionnaire/:id', to: 'diagnostics/primary_certificate#show', as: :primary_certificate_diagnostic
  put '/certificate/primary-certificate/questionnaire/:id', to: 'diagnostics/primary_certificate#update', as: :update_primary_certificate_diagnostic

  namespace 'class_marker' do
    post '/webhook', to: 'webhooks#assessment', as: 'assessment_webhook'
  end

  get '/courses', action: :index, controller: 'courses', as: 'courses'
  get '/courses/:id(/:name)', action: :show, controller: 'courses', as: 'course'

  get '/curriculum', to: 'curriculum/key_stages#index', as: :curriculum_key_stages
  get '/curriculum/:key_stage_slug', to: 'curriculum/key_stages#show', as: :curriculum_key_stage_units
  get '/curriculum/:key_stage_slug/:unit_slug', to: 'curriculum/units#show', as: :curriculum_key_stage_unit
  get '/curriculum/:key_stage_slug/:unit_slug/:lesson_slug', to: 'curriculum/lessons#show', as: :curriculum_key_stage_unit_lesson
  get '/curriculum/rating/units/:polarity/:id', to: 'curriculum/units#rate', as: :curriculum_unit_rating
  get '/curriculum/rating/lessons/:polarity/:id', to: 'curriculum/lessons#rate', as: :curriculum_lesson_rating

  get 'dashboard', action: :show, controller: 'dashboard'

  get '/resources', action: :index, controller: 'resources'
  get '/resources/*redirect_url', action: :show, controller: 'resources', as: 'resources_redirect', format: false

  patch '/users/:id/teacher-reference-number', action: :teacher_reference_number, controller: 'user', as: :user_teacher_reference_number

  get '/404', to: 'pages#exception', defaults: { format: 'html', status: 404 }
  get '/422', to: 'pages#exception', defaults: { status: 422 }
  get '/500', to: 'pages#exception', defaults: { status: 500 }
  get '/about', to: 'pages#page', as: :about, defaults: { page_slug: 'about' }
  get '/accelerator', to: redirect('/cs-accelerator')
  get '/accessibility-statement', to: 'pages#page', as: :accessibility_statement, defaults: { page_slug: 'accessibility-statement' }
  get '/auth/stem', to: redirect('/login')
  get '/auth/callback', to: 'auth#callback', as: 'callback'
  get '/bursary', to: 'cms#cms_page', as: :bursary, defaults: { page_slug: 'bursary' }
  get '/bursary/refresh', to: 'cms#clear_page_cache', defaults: { page_slug: 'bursary' }
  get '/careers-week', to: 'pages#page', as: :careers_week, defaults: { page_slug: 'careers-week' }
  get '/cms/:page_slug', action: :cms_page, controller: :cms, as: :cms_page, defaults: { page_slug: 'hubs' }
  get '/cms/:page_slug/refresh', action: :clear_page_cache, controller: :cms, as: :clear_page_cache, defaults: { page_slug: 'hubs' }
  get '/competition-terms-and-conditions', to: 'pages#page', as: :competition_terms_and_conditions, defaults: { page_slug: 'competition-terms-and-conditions' }
  get '/cs-accelerator', to: 'pages#static_programme_page', as: :cs_accelerator, defaults: { page_slug: 'cs-accelerator' }
  get '/external/assets/ncce.css', to: 'asset_endpoint#css_endpoint', as: :css_endpoint
  get '/faq/courses/', to: 'cms#cms_page', as: :faq_courses, defaults: { page_slug: 'faq-courses' }
  get '/faq/courses/refresh', to: 'cms#clear_page_cache', defaults: { page_slug: 'faq-courses' }
  get '/fl-trailers', to: 'pages#page', as: :trailers, defaults: { page_slug: 'fl-trailers' }
  get '/gender-balance', to: 'pages#page', as: :gender_balance, defaults: { page_slug: 'gender-balance' }
  get '/get-involved', to: 'pages#page', as: :get_involved, defaults: { page_slug: 'get-involved' }
  get '/home-teaching', to: 'pages#page', as: :home_teaching, defaults: { page_slug: 'home-teaching' }
  get '/hero-demo', to: 'pages#page', as: :hero_demo, defaults: { page_slug: 'hero-demo' }
  get '/home-teaching/:page_slug', to: 'cms#cms_page', as: :cms_home_teaching_page, defaults: { page_slug: 'key-stage-1' }
  get '/home-teaching/:page_slug/refresh', to: 'cms#clear_page_cache', as: :clear_home_teaching_page_cache, defaults: { page_slug: 'key-stage-1' }
  get '/hubs', to: 'pages#page', as: :hubs, defaults: { page_slug: 'hubs' }
  get '/login', to: 'pages#login', as: :login
  get '/logout', to: 'auth#logout', as: :logout
  get '/maintenance', to: 'pages#page', as: :maintenance, defaults: { page_slug: 'maintenance' }
  get '/pedagogy', to: 'cms#cms_page', as: :pedagogy, defaults: { page_slug: 'pedagogy' }
  get '/pedagogy/refresh', to: 'cms#clear_page_cache', defaults: { page_slug: 'pedagogy' }
  get '/primary-certificate', to: 'pages#static_programme_page', as: :primary, defaults: { page_slug: 'primary-certificate' },
                              constraints: ->(_request) { Programme.primary_certificate.enrollable? }
  get '/privacy', to: 'pages#page', as: :privacy, defaults: { page_slug: 'privacy' }
  get '/secondary-certificate', to: 'pages#static_programme_page', as: :secondary, defaults: { page_slug: 'secondary-certificate' },
                                constraints: ->(_request) { Programme.secondary_certificate.enrollable? }
  get '/secondary-teachers', to: 'landing_pages#secondary_teachers', as: :secondary_teachers, defaults: { slug: 'cs-accelerator' }
  get '/primary-teachers', to: 'landing_pages#primary_teachers', as: :primary_teachers, defaults: { slug: 'primary-certificate' }
  get '/signup-confirmation', to: 'pages#page', as: :signup_confirmation, defaults: { page_slug: 'signup-confirmation' }
  get '/terms-conditions', to: 'pages#page', as: :terms_conditions, defaults: { page_slug: 'terms-conditions' }
  get '/trailer-demo', to: 'pages#page', defaults: { page_slug: 'trailer-demo' }
  get '/welcome', to: 'welcome#show', as: :welcome

  require 'sidekiq/web'
  mount Sidekiq::Web, at: 'admin/sidekiq'
end

app/controllers/concerns/curriculum/rateable.rb
module Curriculum
  module Rateable
    extend ActiveSupport::Concern

    def rate
      raise MethodMissing unless respond_to?(:client)

      id = params[:id]
      polarity = params[:polarity]

      case polarity.to_sym
      when :positive
        response = client.add_positive_rating(id)
      when :negative
        response = client.add_negative_rating(id)
      else
        raise ArgumentError, "Unexpected polarity: #{polarity}"
      end

      store_rating(id)

      # TODO: Would be better if this text lived in the template
      render json: {
        origin: __method__.to_s,
        message: 'Thank you for your feedback!',
        response: response
      }, status: :ok
    end

    def store_rating(id)
      raw_cookie = cookies[:ratings]
      ratings = raw_cookie.nil? ? [] : JSON.parse(raw_cookie)
      ratings << id
      cookies[:ratings] = JSON.generate(ratings)
    end

    def rating(id)
      raw_cookie = cookies[:ratings]
      ratings = JSON.parse(raw_cookie) unless raw_cookie.nil?
      ratings&.include?(id)
    end
  end
end

app/controllers/curriculum/key_stages_controller.rb
module Curriculum
  class KeyStagesController < ApplicationController
    layout 'full-width'

    before_action :enabled?

    def index
      @key_stages = CurriculumClient::Queries::KeyStage.all.key_stages
    end

    def show
      @key_stage = CurriculumClient::Queries::KeyStage.one(params[:key_stage_slug]).key_stage
    end

    private

      def enabled?
        redirect_to root_path unless curriculum_enabled?
      end
  end
end

app/controllers/curriculum/lessons_controller.rb
module Curriculum
  class LessonsController < ApplicationController
    include Curriculum::Rateable

    layout 'full-width'

    def client
      CurriculumClient::Queries::Lesson
    end

    def show
      @lesson = CurriculumClient::Queries::Lesson.one(params[:lesson_slug]).lesson
      @has_rated = rating(@lesson.id)
    end
  end
end

app/controllers/curriculum/units_controller.rb
module Curriculum
  class UnitsController < ApplicationController
    include Curriculum::Rateable

    layout 'full-width'

    def client
      CurriculumClient::Queries::Unit
    end

    def show
      @unit = CurriculumClient::Queries::Unit.one(params[:unit_slug]).unit
      @has_rated = rating(@unit.id)
    end
  end
end

app/views/curriculum/key_stages/_hero.html.erb
<div class="hero--resources hero hero--bottom-glyph">
  <div class="govuk-width-container">
    <div class="govuk-main-wrapper hero__wrapper">
      <div class="hero__heading-wrapper <%= 'hero__heading-wrapper--full-width' if local_assigns[:full_width] %>">
        <h1 class="govuk-heading-xl hero__heading">Teach computing curriculum</h1>
      </div>
    </div>
  </div>
</div>

app/views/curriculum/key_stages/_key_stages.html.erb
<div class="govuk-grid-row">
  <% key_stages.each do |key_stage| %>
    <div class="govuk-grid-column-one-quarter">
      <div class="<%= ['1', '2'].include?(key_stage.level) ? 'card--orange' : 'card--purple' %> card--resource">
        <h3 class="govuk-heading-m card--resource__title"><%= link_to "#{key_stage.title} resources", curriculum_key_stage_units_path(key_stage_slug: key_stage.slug), class: 'govuk-link ncce-link' %></h3>
        <p class="govuk-body-s"><strong>Year <%= key_stage.years %></strong>, Age <%= key_stage.ages %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/curriculum/key_stages/_resources.html.erb
<div class="govuk-grid-row">
  <% @key_stages.each do |key_stage| %>
    <div class="govuk-grid-column-one-quarter">
      <div class="<%= ['1', '2'].include?(key_stage.level) ? 'card--orange' : 'card--purple' %> card--resource">
        <h3 class="govuk-heading-m card--resource__title"><%= link_to "#{key_stage.title} resources", '', class: 'govuk-link ncce-link' %></h3>
        <p class="govuk-body-s"><strong>Year <%= key_stage.years %></strong>, Age <%= key_stage.ages %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/curriculum/key_stages/_years.html.erb
<% years.each do |year| %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-full">
      <h3 class="govuk-heading-l">Year <%= year.year_number %></h3>
    </div>
  </div>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-full">
      <ul class="govuk-list govuk-body-l govuk-!-padding-bottom-7 govuk-!-padding-top-7">
      <% if year.year_number == '7' %>
        <% year.units.select { |unit| unit.slug == 'impact-of-technology-collaborating-online-respectfully' }.each do |unit| %>
          <li class="curriculum__list--item"><%= link_to unit.title, curriculum_key_stage_unit_path(key_stage_slug: key_stage.slug, unit_slug: unit.slug), class: 'govuk-link ncce-link' %></li>
        <% end %>
        <% year.units.reject { |unit| unit.slug == 'impact-of-technology-collaborating-online-respectfully' }.each do |unit| %>
          <li class="curriculum__list--item"><%= link_to unit.title, curriculum_key_stage_unit_path(key_stage_slug: key_stage.slug, unit_slug: unit.slug), class: 'govuk-link ncce-link' %></li>
        <% end %>
      <% else %>
        <% year.units.each do |unit| %>
          <li class="curriculum__list--item"><%= link_to unit.title, curriculum_key_stage_unit_path(key_stage_slug: key_stage.slug, unit_slug: unit.slug), class: 'govuk-link ncce-link' %></li>
        <% end %>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/curriculum/key_stages/index.html.erb
<% meta_tag :title, 'Curriculum teaching resources' %>
<% meta_tag :description, 'Curriculum resources contain everything you need to teach computing at key stages 1 to 4. Content is free to access, and has been created by subject experts.' %>
<% meta_tag :url, request.original_url %>
<%= render 'hero' %>
<div class="govuk-width-container">
	<div class="govuk-main-wrapper">
		<div class="govuk-grid-row">
			<div class="govuk-grid-column-three-quarters">
				<p class="govuk-body-l">Our curriculum contains everything you need to teach computing at key stages 1 to 4, including lesson plans, slides, worksheets, homework and assessment.</p>
				<p class="govuk-body">All of the content is completely free to access, and has been created by subject experts, based on the latest pedagogical research and teacher feedback.</p>
				<p class="govuk-body">It also provides an innovative progression framework where computing content (concepts, knowledge, skills, and objectives) has been organised into interconnected networks we call learning graphs.</p>
				<p class="govuk-heading-m curriculum__title">Choose resources by key stage</p>
			</div>
		</div>
		<%= render partial: 'key_stages', locals: { key_stages: @key_stages } %>
		<%= render 'curriculum/feedback' %>
	</div>
</div>

app/views/curriculum/key_stages/show.html.erb
<div class="hero hero--resources hero--orange hero--bottom-glyph">
  <div class="govuk-width-container">
    <div class="govuk-main-wrapper hero__wrapper">
      <div class="hero__heading-wrapper <%= 'hero__heading-wrapper--full-width' if local_assigns[:full_width] %>">
        <h1 class="govuk-heading-xl hero__heading">Key stage <%= @key_stage.level %> resources</h1>
      </div>
    </div>
  </div>
</div>
<div class="govuk-width-container">
	<p class="govuk-body govuk-!-padding-top-4 govuk-!-margin-bottom-0"><%= link_to 'Curriculum', curriculum_key_stages_path, class: 'govuk-link ncce-link' %> > <%= @key_stage.short_title %></p>
	<div class="govuk-main-wrapper resources__wrapper external-content">
		<div class="govuk-grid-row">
			<div class="govuk-grid-column-two-thirds">
				<p class="govuk-body-l govuk-!-margin-bottom-8">World-class lesson plans, unit guides and teacher guides to help you <strong>teach computing.</strong></p>
			</div>
		</div>
		<hr class="curriculum__line">
		<%= render partial: 'years', locals: { key_stage: @key_stage, years: @key_stage.year_groups } %>
		<%= render 'curriculum/feedback' %>
	</div>
</div>

app/views/curriculum/key_stages/unit.html.erb
<h3>unit</h3>