config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home', action: :home

  resources :achievements, only: %i[create destroy]

  namespace 'admin' do
    resources :imports
  end

  resources :assessment_attempts

  get '/certificate/:slug', action: :show, controller: 'programmes', as: :programme
  post '/certifcate/:slug/enrol', action: :create, controller: 'user_programme_enrolments', as: :user_programme_enrolment
  get '/certificate/:slug/complete', action: :complete, controller: 'programmes', as: :programme_complete
  get '/certificate/:slug/pending', action: :pending, controller: 'programmes', as: :programme_pending
  get '/certificate/:slug/view-certificate', action: :certificate, controller: 'programmes', as: :programme_certificate
  get '/certificate/cs-accelerator/diagnostic/:id', to: 'diagnostics/cs_accelerator#show', as: :cs_accelerator_diagnostic
  get '/certificate/primary-certificate/questionnaire/:id', to: 'diagnostics/primary_certificate#show', as: :primary_certificate_diagnostic
  put '/certificate/primary-certificate/questionnaire/:id', to: 'diagnostics/primary_certificate#update', as: :update_primary_certificate_diagnostic

  namespace 'class_marker' do
    post '/webhook', to: 'webhooks#assessment', as: 'assessment_webhook'
  end

  get '/courses', action: :index, controller: 'courses', as: 'courses'
  get '/courses/:id(/:name)', action: :show, controller: 'courses', as: 'course'

  get '/curriculum', to: 'curriculum/key_stages#index', as: :curriculum_key_stages
  get '/curriculum/:key_stage_slug', to: 'curriculum/key_stages#show', as: :curriculum_key_stage_units
  get '/curriculum/:key_stage_slug/:unit_slug', to: 'curriculum/units#show', as: :curriculum_key_stage_unit
  get '/curriculum/:key_stage_slug/:unit_slug/:lesson_slug', to: 'curriculum/lessons#show', as: :curriculum_key_stage_unit_lesson
  get '/curriculum/rating/units/:polarity/:id', to: 'curriculum/units#rate', as: :curriculum_unit_rating
  get '/curriculum/rating/lessons/:polarity/:id', to: 'curriculum/lessons#rate', as: :curriculum_lesson_rating

  get 'dashboard', action: :show, controller: 'dashboard'

  get '/resources', action: :index, controller: 'resources'
  get '/resources/*redirect_url', action: :show, controller: 'resources', as: 'resources_redirect', format: false

  patch '/users/:id/teacher-reference-number', action: :teacher_reference_number, controller: 'user', as: :user_teacher_reference_number

  get '/404', to: 'pages#exception', defaults: { format: 'html', status: 404 }
  get '/422', to: 'pages#exception', defaults: { status: 422 }
  get '/500', to: 'pages#exception', defaults: { status: 500 }
  get '/about', to: 'pages#page', as: :about, defaults: { page_slug: 'about' }
  get '/accelerator', to: redirect('/cs-accelerator')
  get '/accessibility-statement', to: 'pages#page', as: :accessibility_statement, defaults: { page_slug: 'accessibility-statement' }
  get '/auth/stem', to: redirect('/login')
  get '/auth/callback', to: 'auth#callback', as: 'callback'
  get '/bursary', to: 'cms#cms_page', as: :bursary, defaults: { page_slug: 'bursary' }
  get '/bursary/refresh', to: 'cms#clear_page_cache', defaults: { page_slug: 'bursary' }
  get '/careers-week', to: 'pages#page', as: :careers_week, defaults: { page_slug: 'careers-week' }
  get '/cms/:page_slug', action: :cms_page, controller: :cms, as: :cms_page, defaults: { page_slug: 'hubs' }
  get '/cms/:page_slug/refresh', action: :clear_page_cache, controller: :cms, as: :clear_page_cache, defaults: { page_slug: 'hubs' }
  get '/competition-terms-and-conditions', to: 'pages#page', as: :competition_terms_and_conditions, defaults: { page_slug: 'competition-terms-and-conditions' }
  get '/cs-accelerator', to: 'pages#static_programme_page', as: :cs_accelerator, defaults: { page_slug: 'cs-accelerator' }
  get '/external/assets/ncce.css', to: 'asset_endpoint#css_endpoint', as: :css_endpoint
  get '/faq/courses/', to: 'cms#cms_page', as: :faq_courses, defaults: { page_slug: 'faq-courses' }
  get '/faq/courses/refresh', to: 'cms#clear_page_cache', defaults: { page_slug: 'faq-courses' }
  get '/fl-trailers', to: 'pages#page', as: :trailers, defaults: { page_slug: 'fl-trailers' }
  get '/gender-balance', to: 'pages#page', as: :gender_balance, defaults: { page_slug: 'gender-balance' }
  get '/get-involved', to: 'pages#page', as: :get_involved, defaults: { page_slug: 'get-involved' }
  get '/home-teaching', to: 'pages#page', as: :home_teaching, defaults: { page_slug: 'home-teaching' }
  get '/hero-demo', to: 'pages#page', as: :hero_demo, defaults: { page_slug: 'hero-demo' }
  get '/home-teaching/:page_slug', to: 'cms#cms_page', as: :cms_home_teaching_page, defaults: { page_slug: 'key-stage-1' }
  get '/home-teaching/:page_slug/refresh', to: 'cms#clear_page_cache', as: :clear_home_teaching_page_cache, defaults: { page_slug: 'key-stage-1' }
  get '/hubs', to: 'pages#page', as: :hubs, defaults: { page_slug: 'hubs' }
  get '/login', to: 'pages#login', as: :login
  get '/logout', to: 'auth#logout', as: :logout
  get '/maintenance', to: 'pages#page', as: :maintenance, defaults: { page_slug: 'maintenance' }
  get '/pedagogy', to: 'cms#cms_page', as: :pedagogy, defaults: { page_slug: 'pedagogy' }
  get '/pedagogy/refresh', to: 'cms#clear_page_cache', defaults: { page_slug: 'pedagogy' }
  get '/primary-certificate', to: 'pages#static_programme_page', as: :primary, defaults: { page_slug: 'primary-certificate' },
                              constraints: ->(_request) { Programme.primary_certificate.enrollable? }
  get '/privacy', to: 'pages#page', as: :privacy, defaults: { page_slug: 'privacy' }
  get '/secondary-certificate', to: 'pages#static_programme_page', as: :secondary, defaults: { page_slug: 'secondary-certificate' },
                                constraints: ->(_request) { Programme.secondary_certificate.enrollable? }
  get '/secondary-teachers', to: 'landing_pages#secondary_teachers', as: :secondary_teachers, defaults: { slug: 'cs-accelerator' }
  get '/primary-teachers', to: 'landing_pages#primary_teachers', as: :primary_teachers, defaults: { slug: 'primary-certificate' }
  get '/signup-confirmation', to: 'pages#page', as: :signup_confirmation, defaults: { page_slug: 'signup-confirmation' }
  get '/terms-conditions', to: 'pages#page', as: :terms_conditions, defaults: { page_slug: 'terms-conditions' }
  get '/trailer-demo', to: 'pages#page', defaults: { page_slug: 'trailer-demo' }
  get '/welcome', to: 'welcome#show', as: :welcome

  require 'sidekiq/web'
  mount Sidekiq::Web, at: 'admin/sidekiq'
end

app/models/certification.rb
class Certification < ApplicationRecord
  has_many :assessments
end

app/views/pages/certification/_hero.html.erb
<div class="hero hero--<%= @programme.slug %> hero--bottom-glyph">
  <div class="govuk-width-container">
    <div class="govuk-main-wrapper hero__wrapper">
      <%= render 'pages/certification/programme-enrolment-status', programme: @programme %>
      <div class="hero__heading-wrapper <%= 'hero__heading-wrapper--full-width' if local_assigns[:full_width] %>">
        <h1 class="govuk-heading-xl hero__heading"><%= @programme.title %></h1>
        <p class="govuk-body hero__text">Certificate awarded by BCS, The Chartered Institute for IT</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/certification/_pathway.html.erb
<div class="pathway-wrapper light-grey-bg">
  <h2 class="govuk-heading-s">Learning pathways for teachers</h2>
	<p class="govuk-body">Our learning pathways will help you to get started and offer a structured route through the programme based on your level of experience.</p>
  <ul class="govuk-list">
		<li class="pathway__item">
			<%= link_to 'Advanced GCSE computer science', 'https://static.teachcomputing.org/pathways/05_Teaching_advanced_GCSE_computer_science.pdf', class: 'govuk-link ncce-link icon-resources' %>
			<span class="pathway__item--pdf">PDF</span>
		</li>
		<li class="pathway__item">
			<%= link_to 'New to GCSE computer science', 'https://static.teachcomputing.org/pathways/02_New_to_GCSE_computer+science.pdf', class: 'govuk-link ncce-link icon-resources' %>
			<span class="pathway__item--pdf">PDF</span>
		</li>
		<li class="pathway__item">
			<%= link_to 'New to algorithms & programming', 'https://static.teachcomputing.org/pathways/03_New_to_algorithms_and_programming.pdf', class: 'govuk-link ncce-link icon-resources' %>
			<span class="pathway__item--pdf">PDF</span>
		</li>
		<li class="pathway__item">
			<%= link_to 'Computing non-specialist', 'https://static.teachcomputing.org/pathways/01_New_to_computing.pdf', class: 'govuk-link ncce-link icon-resources' %>
			<span class="pathway__item--pdf">PDF</span>
		</li>
		<li class="pathway__item">
			<%= link_to 'New to computer systems', 'https://static.teachcomputing.org/pathways/04_New_to_computer_systems.pdf', class: 'govuk-link ncce-link icon-resources' %>
			<span class="pathway__item--pdf">PDF</span>
		</li>
  </ul>
	<%= link_to 'Browse our courses', courses_url(certificate: @programme.slug), class: 'govuk-button button' %>
</div>

app/views/pages/certification/_programme-enrolment-status.html.erb
<% if current_user && programme.user_enrolled?(current_user) %>
  <% case  current_user.user_programme_enrolments.find_by(programme_id: programme.id).current_state %>
    <% when 'enrolled' %>
      <span class="govuk-body-m status-block">You are enrolled</span>
    <% when 'pending' %>
      <span class="govuk-body-m status-block">Programme complete</span>
    <% when 'complete' %>
      <span class="govuk-body-m status-block">Certificate awarded</span>
    <% end %>
<% end %>

app/views/pages/certification/_statement.html.erb
<div class="light-grey-bg">
  <div class="govuk-width-container">
    <div class="govuk-main-wrapper--xl">
			<div class="govuk-grid-row">
				<div class="govuk-grid-column-one-third">
 					<div class="testimonial">
            <p class="govuk-body-s testimonial__text">
              “We’re teaching kids to use technologies that don’t exist yet for problems that they don’t know. It’s going to be a completely different world when they leave school.”
            </p>
            <div class="testimonial__bio">
    					<%= image_tag '/images/careers-week/helen_brant.jpg', alt: 'Helen Brant', class: 'testimonial__image' %>
              <p class="govuk-body-s">
                <strong>Helen Brant</strong><br>
                Music teacher
              </p>
							<p class="govuk-body-s testimonial__bio-cell--span-2">
              <strong><%= link_to 'Read Helen’s interview', 'https://blog.teachcomputing.org/music-computing', class: 'ncce-link ncce-link--contrast axe-skip-a11y-test' %></strong>
            </p>
            </div>
          </div>
				</div>
				<div class="govuk-grid-column-one-third">
 					<div class="testimonial">
            <p class="govuk-body-s testimonial__text">
             “The hard work paid off and studying has made me feel confident teaching computer science. I’m now part of an exciting future.”
            </p>
            <div class="testimonial__bio">
              <%= image_tag '/images/careers-week/julie_simmons.jpg', alt: 'Julie Simmons', class: 'testimonial__image' %>
              <p class="govuk-body-s">
                <strong>Julie Simmons</strong><br>
                English teacher
              </p>
							<p class="govuk-body-s testimonial__bio-cell--span-2">
              <strong><%= link_to 'Read Julie’s interview', 'https://blog.teachcomputing.org/poetry-programming/', class: 'ncce-link ncce-link--contrast axe-skip-a11y-test' %></strong>
            </p>
            </div>
          </div>
				</div>
				<div class="govuk-grid-column-one-third">
           <div class="testimonial">
            <p class="govuk-body-s testimonial__text">
              “I definitely feel more confident as I have picked up a range of skills and techniques that I will be able to use within my classroom and also to enhance my subject knowledge.”
            </p>
            <div class="testimonial__bio">
            	<%= image_tag '/images/careers-week/leroy_david.jpg', alt: 'Leroy David', class: 'testimonial__image' %>
              <p class="govuk-body-s">
                <strong>Leroy David</strong><br>
                Computer science teacher
              </p>
							<p class="govuk-body-s testimonial__bio-cell--span-2">
              <strong><%= link_to 'Read Leroy’s interview', 'https://blog.teachcomputing.org/getting-the-most-from-summer-cpd/', class: 'ncce-link ncce-link--contrast axe-skip-a11y-test' %></strong>
            </p>
            </div>
          </div>
				</div>
			</div>
    </div>
  </div>
</div>