config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home', action: :home

  resources :achievements, only: %i[create destroy]

  namespace 'admin' do
    resources :imports
  end

  resources :assessment_attempts

  get '/certificate/:slug', action: :show, controller: 'programmes', as: :programme
  post '/certifcate/:slug/enrol', action: :create, controller: 'user_programme_enrolments', as: :user_programme_enrolment
  get '/certificate/:slug/complete', action: :complete, controller: 'programmes', as: :programme_complete
  get '/certificate/:slug/pending', action: :pending, controller: 'programmes', as: :programme_pending
  get '/certificate/:slug/view-certificate', action: :certificate, controller: 'programmes', as: :programme_certificate
  get '/certificate/cs-accelerator/diagnostic/:id', to: 'diagnostics/cs_accelerator#show', as: :cs_accelerator_diagnostic
  get '/certificate/primary-certificate/questionnaire/:id', to: 'diagnostics/primary_certificate#show', as: :primary_certificate_diagnostic
  put '/certificate/primary-certificate/questionnaire/:id', to: 'diagnostics/primary_certificate#update', as: :update_primary_certificate_diagnostic

  namespace 'class_marker' do
    post '/webhook', to: 'webhooks#assessment', as: 'assessment_webhook'
  end

  get '/courses', action: :index, controller: 'courses', as: 'courses'
  get '/courses/:id(/:name)', action: :show, controller: 'courses', as: 'course'

  get '/curriculum', to: 'curriculum/key_stages#index', as: :curriculum_key_stages
  get '/curriculum/:key_stage_slug', to: 'curriculum/key_stages#show', as: :curriculum_key_stage_units
  get '/curriculum/:key_stage_slug/:unit_slug', to: 'curriculum/units#show', as: :curriculum_key_stage_unit
  get '/curriculum/:key_stage_slug/:unit_slug/:lesson_slug', to: 'curriculum/lessons#show', as: :curriculum_key_stage_unit_lesson
  get '/curriculum/rating/units/:polarity/:id', to: 'curriculum/units#rate', as: :curriculum_unit_rating
  get '/curriculum/rating/lessons/:polarity/:id', to: 'curriculum/lessons#rate', as: :curriculum_lesson_rating

  get 'dashboard', action: :show, controller: 'dashboard'

  get '/resources', action: :index, controller: 'resources'
  get '/resources/*redirect_url', action: :show, controller: 'resources', as: 'resources_redirect', format: false

  patch '/users/:id/teacher-reference-number', action: :teacher_reference_number, controller: 'user', as: :user_teacher_reference_number

  get '/404', to: 'pages#exception', defaults: { format: 'html', status: 404 }
  get '/422', to: 'pages#exception', defaults: { status: 422 }
  get '/500', to: 'pages#exception', defaults: { status: 500 }
  get '/about', to: 'pages#page', as: :about, defaults: { page_slug: 'about' }
  get '/accelerator', to: redirect('/cs-accelerator')
  get '/accessibility-statement', to: 'pages#page', as: :accessibility_statement, defaults: { page_slug: 'accessibility-statement' }
  get '/auth/stem', to: redirect('/login')
  get '/auth/callback', to: 'auth#callback', as: 'callback'
  get '/bursary', to: 'cms#cms_page', as: :bursary, defaults: { page_slug: 'bursary' }
  get '/bursary/refresh', to: 'cms#clear_page_cache', defaults: { page_slug: 'bursary' }
  get '/careers-week', to: 'pages#page', as: :careers_week, defaults: { page_slug: 'careers-week' }
  get '/cms/:page_slug', action: :cms_page, controller: :cms, as: :cms_page, defaults: { page_slug: 'hubs' }
  get '/cms/:page_slug/refresh', action: :clear_page_cache, controller: :cms, as: :clear_page_cache, defaults: { page_slug: 'hubs' }
  get '/competition-terms-and-conditions', to: 'pages#page', as: :competition_terms_and_conditions, defaults: { page_slug: 'competition-terms-and-conditions' }
  get '/cs-accelerator', to: 'pages#static_programme_page', as: :cs_accelerator, defaults: { page_slug: 'cs-accelerator' }
  get '/external/assets/ncce.css', to: 'asset_endpoint#css_endpoint', as: :css_endpoint
  get '/faq/courses/', to: 'cms#cms_page', as: :faq_courses, defaults: { page_slug: 'faq-courses' }
  get '/faq/courses/refresh', to: 'cms#clear_page_cache', defaults: { page_slug: 'faq-courses' }
  get '/fl-trailers', to: 'pages#page', as: :trailers, defaults: { page_slug: 'fl-trailers' }
  get '/gender-balance', to: 'pages#page', as: :gender_balance, defaults: { page_slug: 'gender-balance' }
  get '/get-involved', to: 'pages#page', as: :get_involved, defaults: { page_slug: 'get-involved' }
  get '/home-teaching', to: 'pages#page', as: :home_teaching, defaults: { page_slug: 'home-teaching' }
  get '/hero-demo', to: 'pages#page', as: :hero_demo, defaults: { page_slug: 'hero-demo' }
  get '/home-teaching/:page_slug', to: 'cms#cms_page', as: :cms_home_teaching_page, defaults: { page_slug: 'key-stage-1' }
  get '/home-teaching/:page_slug/refresh', to: 'cms#clear_page_cache', as: :clear_home_teaching_page_cache, defaults: { page_slug: 'key-stage-1' }
  get '/hubs', to: 'pages#page', as: :hubs, defaults: { page_slug: 'hubs' }
  get '/login', to: 'pages#login', as: :login
  get '/logout', to: 'auth#logout', as: :logout
  get '/maintenance', to: 'pages#page', as: :maintenance, defaults: { page_slug: 'maintenance' }
  get '/pedagogy', to: 'cms#cms_page', as: :pedagogy, defaults: { page_slug: 'pedagogy' }
  get '/pedagogy/refresh', to: 'cms#clear_page_cache', defaults: { page_slug: 'pedagogy' }
  get '/primary-certificate', to: 'pages#static_programme_page', as: :primary, defaults: { page_slug: 'primary-certificate' },
                              constraints: ->(_request) { Programme.primary_certificate.enrollable? }
  get '/privacy', to: 'pages#page', as: :privacy, defaults: { page_slug: 'privacy' }
  get '/secondary-certificate', to: 'pages#static_programme_page', as: :secondary, defaults: { page_slug: 'secondary-certificate' },
                                constraints: ->(_request) { Programme.secondary_certificate.enrollable? }
  get '/secondary-teachers', to: 'landing_pages#secondary_teachers', as: :secondary_teachers, defaults: { slug: 'cs-accelerator' }
  get '/primary-teachers', to: 'landing_pages#primary_teachers', as: :primary_teachers, defaults: { slug: 'primary-certificate' }
  get '/signup-confirmation', to: 'pages#page', as: :signup_confirmation, defaults: { page_slug: 'signup-confirmation' }
  get '/terms-conditions', to: 'pages#page', as: :terms_conditions, defaults: { page_slug: 'terms-conditions' }
  get '/trailer-demo', to: 'pages#page', defaults: { page_slug: 'trailer-demo' }
  get '/welcome', to: 'welcome#show', as: :welcome

  require 'sidekiq/web'
  mount Sidekiq::Web, at: 'admin/sidekiq'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'full-width'
  before_action :authenticate_user!
  before_action :store_internal_location

  def show
    @achievements = current_user.achievements.in_state(:complete)
                                .without_category('action').order('created_at ASC')
    render :show
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def has_user_completed_activity?(user, activity)
    return false if user.blank? || activity.blank?
    user.achievements.any? { |a| a.activity.id == activity.id }
  end
end

app/views/pages/dashboard/course.html.erb
<h1>Course</h1>
<p><strong>activity_title:</strong> <%= @course.activity_title %></p>
<p><strong>start_date:</strong> <%= @course.start_date %></p>
<p><strong>end_date:</strong> <%= @course.end_date %></p>
<p><strong>activity_code:</strong> <%= @course.activity_code %></p>
<p><strong>summary:</strong> <%= @course.summary %></p>
<p><strong>outcomes:</strong> <%= @course.outcomes %></p>
<p><strong>places_remaining:</strong> <%= @course.places_remaining %></p>
<p><strong>topic:</strong> <%= @course.topic %></p>
<p><strong>meta_description:</strong> <%= @course.meta_description %></p>
<p><strong>additional_information:</strong> <%= @course.additional_information %></p>
<p><strong>portal_course_url:</strong> <%= @course.portal_course_url %></p>
<p><strong>session_start_time:</strong> <%= @course.session_start_time %></p>
<p><strong>session_end_time:</strong> <%= @course.session_end_time %></p>
<p><strong>instance_code:</strong> <%= @course.instance_code %></p>
<p><strong>deliverer:</strong> <%= @course.deliverer %></p>
<p><strong>template_duration_period:</strong> <%= @course.template_duration_period %></p>
<p><strong>template_duration_no:</strong> <%= @course.template_duration_no %></p>
<p><strong>duration_period:</strong> <%= @course.duration_period %></p>
<p><strong>duration_no:</strong> <%= @course.duration_no %></p>
<p><strong>address_venue_name:</strong> <%= @course.address_venue_name %></p>
<p><strong>address_venue_code:</strong> <%= @course.address_venue_code %></p>
<p><strong>address_town:</strong> <%= @course.address_town %></p>
<p><strong>address_postcode:</strong> <%= @course.address_postcode %></p>
<p><strong>address_line_1:</strong> <%= @course.address_line_1 %></p>
<p><strong>address_no:</strong> <%= @course.address_no %></p>
<p><strong>template_title:</strong> <%= @course.template_title %></p>
<p><strong>status:</strong> <%= @course.status %></p>
<p><strong>fee:</strong> <%= @course.fee %></p>
<p><strong>pay_later:</strong> <%= @course.pay_later %></p>
<p><strong>epayment:</strong> <%= @course.epayment %></p>
<p><strong>changed_date:</strong> <%= @course.changed_date %></p>
<p><strong>everest_occurrence_changed_date:</strong> <%= @course.everest_occurrence_changed_date %></p>
<p><strong>cpd_type:</strong> <%= @course.cpd_type %></p>
<p><strong>display_programme:</strong> <%= @course.display_programme %></p>
<p><strong>itk_cpd_type:</strong> <%= @course.itk_cpd_type %></p>
<p><strong>imported_to_itk:</strong> <%= @course.imported_to_itk %></p>
<p><strong>award_value:</strong> <%= @course.award_value %></p>
<p><strong>fee_category:</strong> <%= @course.fee_category %></p>
<p><strong>course_occurrence_no:</strong> <%= @course.course_occurrence_no %></p>
<p><strong>course_template_no:</strong> <%= @course.course_template_no %></p>

app/views/pages/dashboard/courses.html.erb
<h1 class="govuk-heading-xl">Dashboard</h1>
<h2 class="govuk-heading-l">Courses</h2>
<p class="govuk-body">The online courses are available on FutureLearn.</p>
<p class="govuk-body">The face to face courses are at hubs/universities.</p>
<p class="govuk-body">After you complete the course, come back here to the NCCE to track your progress towards certification.</p>

<table class="govuk-table">
  <thead class="govuk-table__head">
    <tr class="govuk-table__row">
      <th class="govuk-table__header" scope="col">Course Name</th>
      <th class="govuk-table__header" scope="col">Course Type</th>
    </tr>
  </thead>
  <tbody class="govuk-table__body">
    <% @courses.each do |course| %>
    <tr class="govuk-table__row">
      <th class="govuk-table__header" scope="row"><%= link_to course.activity_title, course_url({:id => course.course_occurrence_no}), {:class => 'govuk-link'} %></th>
      <td class="govuk-table__cell">Face To Face</td>
    </tr>
    <% end %>
  </tbody>
</table>