config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home', action: :home

  resources :achievements, only: %i[create destroy]

  namespace 'admin' do
    resources :imports
  end

  resources :assessment_attempts

  get '/certificate/:slug', action: :show, controller: 'programmes', as: :programme
  post '/certifcate/:slug/enrol', action: :create, controller: 'user_programme_enrolments', as: :user_programme_enrolment
  get '/certificate/:slug/complete', action: :complete, controller: 'programmes', as: :programme_complete
  get '/certificate/:slug/pending', action: :pending, controller: 'programmes', as: :programme_pending
  get '/certificate/:slug/view-certificate', action: :certificate, controller: 'programmes', as: :programme_certificate
  get '/certificate/cs-accelerator/diagnostic/:id', to: 'diagnostics/cs_accelerator#show', as: :cs_accelerator_diagnostic
  get '/certificate/primary-certificate/questionnaire/:id', to: 'diagnostics/primary_certificate#show', as: :primary_certificate_diagnostic
  put '/certificate/primary-certificate/questionnaire/:id', to: 'diagnostics/primary_certificate#update', as: :update_primary_certificate_diagnostic

  namespace 'class_marker' do
    post '/webhook', to: 'webhooks#assessment', as: 'assessment_webhook'
  end

  get '/courses', action: :index, controller: 'courses', as: 'courses'
  get '/courses/:id(/:name)', action: :show, controller: 'courses', as: 'course'

  get '/curriculum', to: 'curriculum/key_stages#index', as: :curriculum_key_stages
  get '/curriculum/:key_stage_slug', to: 'curriculum/key_stages#show', as: :curriculum_key_stage_units
  get '/curriculum/:key_stage_slug/:unit_slug', to: 'curriculum/units#show', as: :curriculum_key_stage_unit
  get '/curriculum/:key_stage_slug/:unit_slug/:lesson_slug', to: 'curriculum/lessons#show', as: :curriculum_key_stage_unit_lesson
  get '/curriculum/rating/units/:polarity/:id', to: 'curriculum/units#rate', as: :curriculum_unit_rating
  get '/curriculum/rating/lessons/:polarity/:id', to: 'curriculum/lessons#rate', as: :curriculum_lesson_rating

  get 'dashboard', action: :show, controller: 'dashboard'

  get '/resources', action: :index, controller: 'resources'
  get '/resources/*redirect_url', action: :show, controller: 'resources', as: 'resources_redirect', format: false

  patch '/users/:id/teacher-reference-number', action: :teacher_reference_number, controller: 'user', as: :user_teacher_reference_number

  get '/404', to: 'pages#exception', defaults: { format: 'html', status: 404 }
  get '/422', to: 'pages#exception', defaults: { status: 422 }
  get '/500', to: 'pages#exception', defaults: { status: 500 }
  get '/about', to: 'pages#page', as: :about, defaults: { page_slug: 'about' }
  get '/accelerator', to: redirect('/cs-accelerator')
  get '/accessibility-statement', to: 'pages#page', as: :accessibility_statement, defaults: { page_slug: 'accessibility-statement' }
  get '/auth/stem', to: redirect('/login')
  get '/auth/callback', to: 'auth#callback', as: 'callback'
  get '/bursary', to: 'cms#cms_page', as: :bursary, defaults: { page_slug: 'bursary' }
  get '/bursary/refresh', to: 'cms#clear_page_cache', defaults: { page_slug: 'bursary' }
  get '/careers-week', to: 'pages#page', as: :careers_week, defaults: { page_slug: 'careers-week' }
  get '/cms/:page_slug', action: :cms_page, controller: :cms, as: :cms_page, defaults: { page_slug: 'hubs' }
  get '/cms/:page_slug/refresh', action: :clear_page_cache, controller: :cms, as: :clear_page_cache, defaults: { page_slug: 'hubs' }
  get '/competition-terms-and-conditions', to: 'pages#page', as: :competition_terms_and_conditions, defaults: { page_slug: 'competition-terms-and-conditions' }
  get '/cs-accelerator', to: 'pages#static_programme_page', as: :cs_accelerator, defaults: { page_slug: 'cs-accelerator' }
  get '/external/assets/ncce.css', to: 'asset_endpoint#css_endpoint', as: :css_endpoint
  get '/faq/courses/', to: 'cms#cms_page', as: :faq_courses, defaults: { page_slug: 'faq-courses' }
  get '/faq/courses/refresh', to: 'cms#clear_page_cache', defaults: { page_slug: 'faq-courses' }
  get '/fl-trailers', to: 'pages#page', as: :trailers, defaults: { page_slug: 'fl-trailers' }
  get '/gender-balance', to: 'pages#page', as: :gender_balance, defaults: { page_slug: 'gender-balance' }
  get '/get-involved', to: 'pages#page', as: :get_involved, defaults: { page_slug: 'get-involved' }
  get '/home-teaching', to: 'pages#page', as: :home_teaching, defaults: { page_slug: 'home-teaching' }
  get '/hero-demo', to: 'pages#page', as: :hero_demo, defaults: { page_slug: 'hero-demo' }
  get '/home-teaching/:page_slug', to: 'cms#cms_page', as: :cms_home_teaching_page, defaults: { page_slug: 'key-stage-1' }
  get '/home-teaching/:page_slug/refresh', to: 'cms#clear_page_cache', as: :clear_home_teaching_page_cache, defaults: { page_slug: 'key-stage-1' }
  get '/hubs', to: 'pages#page', as: :hubs, defaults: { page_slug: 'hubs' }
  get '/login', to: 'pages#login', as: :login
  get '/logout', to: 'auth#logout', as: :logout
  get '/maintenance', to: 'pages#page', as: :maintenance, defaults: { page_slug: 'maintenance' }
  get '/pedagogy', to: 'cms#cms_page', as: :pedagogy, defaults: { page_slug: 'pedagogy' }
  get '/pedagogy/refresh', to: 'cms#clear_page_cache', defaults: { page_slug: 'pedagogy' }
  get '/primary-certificate', to: 'pages#static_programme_page', as: :primary, defaults: { page_slug: 'primary-certificate' },
                              constraints: ->(_request) { Programme.primary_certificate.enrollable? }
  get '/privacy', to: 'pages#page', as: :privacy, defaults: { page_slug: 'privacy' }
  get '/secondary-certificate', to: 'pages#static_programme_page', as: :secondary, defaults: { page_slug: 'secondary-certificate' },
                                constraints: ->(_request) { Programme.secondary_certificate.enrollable? }
  get '/secondary-teachers', to: 'landing_pages#secondary_teachers', as: :secondary_teachers, defaults: { slug: 'cs-accelerator' }
  get '/primary-teachers', to: 'landing_pages#primary_teachers', as: :primary_teachers, defaults: { slug: 'primary-certificate' }
  get '/signup-confirmation', to: 'pages#page', as: :signup_confirmation, defaults: { page_slug: 'signup-confirmation' }
  get '/terms-conditions', to: 'pages#page', as: :terms_conditions, defaults: { page_slug: 'terms-conditions' }
  get '/trailer-demo', to: 'pages#page', defaults: { page_slug: 'trailer-demo' }
  get '/welcome', to: 'welcome#show', as: :welcome

  require 'sidekiq/web'
  mount Sidekiq::Web, at: 'admin/sidekiq'
end

app/views/resources/_aside.html.erb
<div class="resources-aside">
  <h4 class="govuk-heading-s resources-aside__title">Package contents
  </h4>
  <ul class="govuk-list" arial-role="list">
    <li>Lesson plans</li>
    <li>Learning graphs</li>
    <li>Unit overviews</li>
    <li>Activities</li>
    <% unless year.to_i <= 2 %>
      <li>Assessments</li>
      <li>Homework</li>
    <% end %>
  </ul>
  <p class="govuk-body">
  <% if live %>
    <%= link_to_if current_user, "Access year #{year} resources", resources_redirect_path(redirect_url: URI.encode_www_form_component(resource_url), year: year), class: 'govuk-button button--aside', role: 'button', draggable: 'false' do
        link_to 'Log in to access', "#{auth_url}?source_uri=#{URI.escape(request.original_url + '#year-' + year.to_s)}", method: :post, class: 'govuk-button button--aside', role: 'button', draggable: 'false'
    end %>
  <% else %>
    <%= button_to 'Coming soon', '#', class: 'govuk-button button--aside', role: 'button', draggable: 'false', disabled: true %>
  <% end %>
  </p>
</div>

app/views/resources/_key-stage-header.html.erb
<div class="resources-key-stage">
  <div class="govuk-width-container">
    <div class="govuk-main-wrapper resources-key-stage__wrapper">
      <h2 id="<%= "key-stage-#{key_stage}" %>" class="govuk-heading-m resources-key-stage__heading">Key stage <%= "#{key_stage}" %></h2>
    </div>
  </div>
</div>

app/views/resources/_year-1.html.erb
<div class="resources-year">
  <h3 id="year-1" class="govuk-heading-m resources-year__heading">Year 1</h3>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <ul class="govuk-list resources-year__lesson-list" aria-role="list">
				<li>
          <h4 class="govuk-heading-s resources-year__title">Grouping data</h4>
          <p class="govuk-body">This unit introduces pupils to data and information. They will begin by using labels to put objects into groups, and labelling these groups. Pupils will demonstrate that they can count a small number of objects, before and after the objects are grouped. They will then begin to demonstrate their ability to sort objects into different groups, based on the properties they choose. Finally, pupils will use their ability to sort objects into different groups to answer questions about data.</p>
        </li>
				<li>
          <h4 class="govuk-heading-s resources-year__title">Programming A – Moving a robot</h4>
          <p class="govuk-body">This unit introduces learners to early programming concepts. Learners will explore using individual commands, both with other learners and as part of a computer program. They will identify what each floor robot command does and use that knowledge to start predicting the outcome of programs. The unit is paced to ensure time is spent on all aspects of programming and builds knowledge in a structured manner. Learners are also introduced to the early stages of program design through the introduction of algorithms.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Computing Systems
            and Networks – Technology Around Us</h4>
          <p class="govuk-body">Develop your learners’ understanding of
            technology and how it can help them. They will become more familiar
            with the different components of a computer by developing their
            keyboard and mouse skills, and also start to consider how to use
            technology responsibly.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Creating Media –
            Digital Painting</h4>
          <p class="govuk-body">Explore the world of digital art and its
            exciting range of creative tools with your learners. Empower them to
            create their own paintings, while getting inspiration from a range
            of other artists. Conclude by asking them to consider their
            preferences when painting with, and without, the use of digital
            devices.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Creating Media –
            Digital Writing</h4>
          <p class="govuk-body">Promote your learners’ understanding of the
            various aspects of using a computer to create and change text.
            Learners will familiarise themselves with typing on a keyboard and
            begin using tools to change the look of their writing, and then they
            will consider the differences between using a computer and writing
            on paper to create text.</p>
        </li>
      </ul>
    </div>
    <div class="govuk-grid-column-one-third">
      <%= render 'aside', year: 1, resource_url: 'https://ncce.io/Year1', live: true %>
    </div>
  </div>
</div>

app/views/resources/_year-10-11.html.erb
<div class="resources-year">
  <h3 id="year-10-11" class="govuk-heading-m resources-year__heading">Years 10 &
    11
  </h3>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <ul class="govuk-list resources-year__lesson-list" aria-role="list">
				<li>
          <h4 class="govuk-heading-s resources-year__title">IT Project Management</h4>
          <p class="govuk-body">Project management has numerous transferable skills for learners, from simple time management to structured project management techniques. These skills will be invaluable for learners in their future careers. It will support team building, enable learners to become more organised, and allow them to reflect on any work completed.</p>
        </li>
				<li>
          <h4 class="govuk-heading-s resources-year__title">Data Representations</h4>
          <p class="govuk-body">This unit allows learners to gain the understanding and skills required for the data representation sections of the GCSE computer science exam. First, learners look at binary and hexadecimal numbering systems, how they work, and how to convert between bases. Then, learners explore different coding systems and find out how text, images, and sound are represented in computers. All lessons include worksheets to allow learners to explore each topic through practical application.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">IT and the World of
            Work</h4>
          <p class="govuk-body">The world of work has been transformed by the
            use of information technologies. Learners must be able to identify
            how the modern structure of the workplace will impact their future
            lives. This unit will facilitate a deeper comprehension of the
            methods employed by organisations and the impact the use of IT in
            the working environment has on all stakeholders.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Networks</h4>
          <p class="govuk-body">This unit guides learners to gain an
            understanding of computer networks as required for GCSE Computer
            Science. It starts by defining what networks are and where we find
            them in our modern world. Then, learners look at the hardware
            involved in creating networks. In this unit, you will use Raspberry
            Pi computers to create a network and demonstrate to learners how
            data is shared across networks.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Security</h4>
          <p class="govuk-body">This unit enables students to gain knowledge and
            understanding of the range of cybersecurity threats impacting the
            world, our organisations, as well as us as individuals. Learners
            will explore security measures that can be put in place to protect
            networks and your data against different forms of automated and
            non-automated forms of attack. Once they have understood the impact
            of cybercrime, they will be inspired to be part of the solution,
            when they learn about the potential for lucrative and fulfilling
            careers in cybersecurity.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Spreadsheets</h4>
          <p class="govuk-body">In this unit, learners will gain an
            understanding and knowledge of how to use spreadsheets to store and
            manipulate data, how to use common functions, and how to extract
            data to create visual representations using charts. Learners will
            use spreadsheets to track and calculate income, make predictions,
            and answer “what if…?” questions. It is assumed that learners have
            had some experience of spreadsheets at KS3 level and therefore know
            how to use cell references, fill colours, and borders, and are
            familiar with the basic functions, e.g. SUM, AVERAGE, MAX, and MIN.
          </p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Online Safety</h4>
          <p class="govuk-body">
            As most learners will already have some form of online presence and
            familiarity with online spaces, the purpose of this unit is for them
            to start thinking more critically about how they, and others, conduct
            themselves online. Learners will also be asked to discuss key debates
            around the online world, such as the extent of their right to privacy,
            and which powers should be granted to organisations and states. As
            much as possible, learners should be encouraged to develop their own
            ideas and opinions in order to become engaged citizens when it comes
            to online rights.
          </p>
        </li>
      </ul>
    </div>
    <div class="govuk-grid-column-one-third">
      <%= render 'aside', year: '10 & 11', resource_url: 'https://ncce.io/ks4', live: true %>
    </div>
  </div>
</div>

app/views/resources/_year-2.html.erb
<div class="resources-year">
  <h3 id="year-2" class="govuk-heading-m resources-year__heading">Year 2</h3>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <ul class="govuk-list resources-year__lesson-list" aria-role="list">
        <li>
          <h4 class="govuk-heading-s resources-year__title">Programming A – Robot algorithms</h4>
          <p class="govuk-body">This unit develops pupils’ understanding of instructions in sequences and the use of logical reasoning to predict outcomes. Pupils will use given commands in different orders to investigate how the order affects the outcome. Pupils will also learn about design in programming. They will develop artwork and test it for use in a program. They will design algorithms and then test those algorithms as programs and debug them.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Data and Information – Pictograms</h4>
          <p class="govuk-body">This unit introduces the learners to the term ‘data’. Learners will begin to understand what data means and how this can be collected in the form of a tally chart. They will learn the term ‘attribute’ and use this to help them organise data. They will then progress onto presenting data in the form of pictograms and finally block diagrams. Learners will use the data presented to answer questions.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Computing Systems
            and Networks – Information Technology Around Us</h4>
          <p class="govuk-body">How is information technology (IT) being used
            for good in our lives? With an initial focus on IT in the home,
            learners explore how IT benefits society in places such as shops,
            libraries, and hospitals. Whilst discussing the responsible use of
            technology, and how to make smart choices when using it.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Creating media –
            Digital photography</h4>
          <p class="govuk-body">Through the lessons in this unit, learners will
            learn to recognise that different devices can be used to capture
            photographs and will gain experience capturing, editing, and
            improving photos. Finally, they will use this knowledge to recognise
            that images they see may not be real.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Creating Media –
            Making Music</h4>
          <p class="govuk-body">Learners will explore how music can make them
            think and feel. They will make patterns and use those patterns to
            make music with both percussion instruments and digital tools. They
            will also create different rhythms and tunes, using the movement of
            animals for inspiration. Finally, learners will share their
            creations and compare creating music digitally and non-digitally.
          </p>
        </li>
      </ul>
    </div>
    <div class="govuk-grid-column-one-third">
      <%= render 'aside', year: 2, resource_url: 'https://ncce.io/Year2', live: true %>
    </div>
  </div>
</div>

app/views/resources/_year-3.html.erb
<div class="resources-year">
  <h3 id="year-3" class="govuk-heading-m resources-year__heading">Year 3</h3>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <ul class="govuk-list resources-year__lesson-list" aria-role="list">
        <li>
          <h4 class="govuk-heading-s resources-year__title">Programming A – Sequence in music</h4>
          <p class="govuk-body">This unit explores the concept of sequencing in programming through Scratch. It begins with an introduction to the programming environment, which will be new to most learners. They will be introduced to a selection of motion, sound, and event blocks which they will use to create their own programs, featuring sequences. The final project is to make a representation of a piano. The unit is paced to focus on all aspects of sequences, and make sure that knowledge is built in a structured manner. Learners also apply stages of program design through this unit.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Computing Systems
            and Networks – Connecting Computers</h4>
          <p class="govuk-body">Challenge your learners to develop their
            understanding of digital devices, with an initial focus on inputs,
            processes, and outputs. Start by comparing digital and non-digital
            devices, before introducing them to computer networks that include
            network infrastructure devices like routers and switches.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Creating media – Desktop publishing</h4>
          <p class="govuk-body">During this unit, learners will become familiar with the terms ‘text’ and ‘images’ and understand that they can be used to communicate messages. They will use desktop publishing software and consider careful choices of font size, colour and type to edit and improve premade documents. Learners will be introduced to the terms ‘templates’, ‘orientation’, and ‘placeholders’ and begin to understand how these can support them in making their own template for a magazine front cover. They will start to add text and images to create their own pieces of work using desktop publishing software. Learners will look at a range of page layouts thinking carefully about the purpose of these and evaluate how and why desktop publishing is used in the real world.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Creating Media –
            Stop frame animation</h4>
          <p class="govuk-body">During this unit, learners will use a range of
            techniques to create a stop frame animation using tablets. Next,
            they will apply those skills to create a story-based animation. This
            unit will conclude with learners adding other types of media to
            their animation, such as music and text.</p>
        </li>
      </ul>
    </div>
    <div class="govuk-grid-column-one-third">
      <%= render 'aside', year: 3, resource_url: 'https://ncce.io/Year3', live: true %>
    </div>
  </div>
</div>

app/views/resources/_year-4.html.erb
<div class="resources-year">
  <h3 id="year-4" class="govuk-heading-m resources-year__heading">Year 4</h3>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <ul class="govuk-list resources-year__lesson-list" aria-role="list">
				<li>
          <h4 class="govuk-heading-s resources-year__title">Programming A – Repetition in shapes</h4>
          <p class="govuk-body">This unit is the first of the two programming units in Year 4, and looks at repetition and loops within programming. Pupils will create programs by planning, modifying, and testing commands to create shapes and patterns. They will use Logo, a text-based programming language.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Computing systems
            and networks – The internet</h4>
          <p class="govuk-body">During this unit learners will apply their
            knowledge and understanding of networks, to appreciate the internet
            as a network of networks which need to be kept secure. They will
            learn that the World Wide Web is part of the internet, and be given
            opportunities to explore the World Wide Web for themselves to learn
            about who owns content and what they can access, add, and create.
            Finally they will evaluate online content to decide how honest,
            accurate, or reliable it is, and understand the consequences of
            false information.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Creating media –
            Audio editing</h4>
          <p class="govuk-body">In this unit, learners will initially examine
            devices capable of recording digital audio, which will include
            identifying the input device (microphone) and output devices
            (speaker or headphones) if available. Learners will discuss the
            ownership of digital audio and the copyright implications of
            duplicating the work of others. In order to record audio themselves,
            learners will use Audacity to produce a podcast, which will include
            editing their work, adding multiple tracks, and opening and saving
            the audio files. Finally, learners will evaluate their work and give
            feedback to their peers.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Creating media –
            Photo editing</h4>
          <p class="govuk-body">In this unit, learners will develop their
            understanding of how digital images can be changed and edited, and
            how they can then be resaved and reused. They will consider the
            impact that editing images can have, and evaluate the effectiveness
            of their choices.</p>
        </li>
      </ul>
    </div>
    <div class="govuk-grid-column-one-third">
      <%= render 'aside', year: 4, resource_url: 'https://ncce.io/Year4', live: true %>
    </div>
  </div>
</div>

app/views/resources/_year-5.html.erb
<div class="resources-year">
  <h3 id="year-5" class="govuk-heading-m resources-year__heading">Year 5</h3>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <ul class="govuk-list resources-year__lesson-list" aria-role="list">
        <li>
          <h4 class="govuk-heading-s resources-year__title">Flat-file Databases</h4>
          <p class="govuk-body">This unit looks at how a flat-file database can be used to organise data in records. Pupils use tools within a database to order and answer questions about data. They create graphs and charts from their data to help solve problems. They use a real-life database to answer a question, and present their work to others.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Computing systems
            and networks – Sharing information</h4>
          <p class="govuk-body">In this unit, learners will develop their
            understanding of computer systems and how information is transferred
            between systems and devices. Learners will consider small-scale
            systems as well as large-scale systems. They will explain the input,
            output, and process aspects of a variety of different real-world
            systems. Learners will also take part in a collaborative online
            project with other class members and develop their skills in working
            together online.</p>
        </li>
 				<li>
          <h4 class="govuk-heading-s resources-year__title">Creating media – Vector drawing</h4>
          <p class="govuk-body">In this unit learners will find out that vector images are made up of shapes. They will learn how to use the different drawing tools and how images are created in layers. They will explore the ways in which images can be grouped and duplicated to support them in creating more complex pieces of work. This unit is planned using the Google Drawings app other alternative pieces of software are available.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Creating media – Video editing</h4>
          <p class="govuk-body">This unit gives learners the opportunity to learn how to create short videos in groups.
          As they progress through this unit, they will be exposed to topic-based language and develop the skills of
          capturing, editing, and manipulating video. Active learning is encouraged through guided questions and by
          working in small groups to investigate the use of devices and software. Learners are guided with step-by-step
          support to take their idea from conception to completion. At the teacher’s discretion, the use of green screen
          can be incorporated into this unit. At the conclusion of the unit, learners have the opportunity to reflect on
          and assess their progress in creating a video.</p>
        </li>
      </ul>
    </div>
    <div class="govuk-grid-column-one-third">
      <%= render 'aside', year: 5, resource_url: 'https://ncce.io/Year5', live: true %>
    </div>
  </div>
</div>

app/views/resources/_year-6.html.erb
<div class="resources-year">
  <h3 id="year-6" class="govuk-heading-m resources-year__heading">Year 6</h3>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <ul class="govuk-list resources-year__lesson-list" aria-role="list">
				<li>
          <h4 class="govuk-heading-s resources-year__title">Creating Media – 3D Modelling</h4>
          <p class="govuk-body">During this unit, learners will develop their knowledge and understanding of using a computer to produce 3D models. Learners will initially familiarise themselves with working in a 3D space, including combining 3D objects to make a house and examining the differences between working digitally with 2D and 3D graphics. Learners will progress to making accurate 3D models of physical objects, such as a pencil holder, which include using 3D objects as placeholders. Finally, learners will examine the need to group 3D objects, then go on to plan, develop, and evaluate their own 3D model of a photo frame.</p>
        </li>
				<li>
          <h4 class="govuk-heading-s resources-year__title">Creating media – Web page creation</h4>
          <p class="govuk-body">This unit introduces learners to the creation of websites for a chosen purpose. Learners identify what makes a good web page and use this information to design and evaluate their own website using Google Sites. Throughout the process learners pay specific attention to copyright and fair use of media, the aesthetics of the site, and navigation paths.</p>
        </li>
        <li>
          <h4 class="govuk-heading-s resources-year__title">Computing systems and networks – Communication</h4>
          <p class="govuk-body">In this unit, the class will learn about the World Wide Web as a communication tool. First, they will learn how we find information on the World Wide Web, through learning how search engines work (including how they select and rank results) and what influences searching, and through comparing different search engines. They will then investigate different methods of communication, before focusing on internet-based communication. Finally, they will evaluate which methods of internet communication to use for particular purposes.</p>
        </li>
      </ul>
    </div>
    <div class="govuk-grid-column-one-third">
      <%= render 'aside', year: 6, resource_url: 'https://ncce.io/Year6', live: true %>
    </div>
  </div>
</div>